[package]
name = "school_password_crack"
version = "2.1.7"
authors = ["Connor Slade <connor@connorcode.com>"]
edition = "2018"

[dependencies]
ureq = { version = "2.1.1", features = ["cookies"] }
regex = "1.5.4"
home = "0.5.3"
