[package]
name = "school_password_crack"
version = "0.1.0"
authors = ["Connor Slade <connor@connorcode.com>"]
edition = "2018"

[dependencies]
ureq = { version = "2.1.1", features = ["cookies"] }
regex = "1.5.4"
micro_rand = "0.0.1"
home = "0.5.3"